spring.application.name=Car-rental-system

spring.datasource.url=jdbc:postgresql://localhost:5432/car_rental
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
